from pathlib import Path
from .ir import ServiceIR


def generate_mcp_server(service_ir: ServiceIR, output_dir):
    """
    Generate a FastMCP server Python file from ServiceIR.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    server_file = output_path / "server.py"

    with open(server_file, "w") as f:
        # Header
        f.write('"""\n')
        f.write("AUTO-GENERATED FILE\n")
        f.write("-------------------\n")
        f.write("This MCP server was generated automatically from an OpenAPI specification.\n")
        f.write("Do NOT edit this file manually.\n")
        f.write('"""\n\n')

        # Imports
        f.write("from mcp.server.fastmcp import FastMCP\n")
        f.write("import uuid\n")
        f.write("import random\n\n")

        # Server init
        f.write(f'mcp = FastMCP("{service_ir.service_name}")\n\n')

        # Generate tools
        for tool in service_ir.tools:
            f.write("# -----------------------------\n")
            f.write(f"# Tool: {tool.name}\n")
            f.write("# -----------------------------\n")
            f.write("@mcp.tool()\n")
            f.write(f"def {tool.name}(input: dict) -> dict:\n")
            f.write('    """\n')
            f.write(f"    {tool.description or tool.name}\n")
            f.write('    """\n')

            # Simple heuristic-based mock logic
            if "menu" in tool.name.lower():
                f.write(
                    "    return {\n"
                    "        \"menu\": [\n"
                    "            {\"name\": \"Margherita\", \"size\": \"Medium\", \"price\": 8.99},\n"
                    "            {\"name\": \"Pepperoni\", \"size\": \"Large\", \"price\": 12.99},\n"
                    "            {\"name\": \"Veggie\", \"size\": \"Small\", \"price\": 7.49},\n"
                    "        ]\n"
                    "    }\n\n\n"
                )

            elif "order" in tool.name.lower() and "track" not in tool.name.lower():
                f.write(
                    "    order_id = str(uuid.uuid4())[:8]\n"
                    "    return {\n"
                    "        \"order_id\": order_id,\n"
                    "        \"eta_minutes\": random.randint(15, 30)\n"
                    "    }\n\n\n"
                )

            elif "track" in tool.name.lower():
                f.write(
                    "    return {\n"
                    "        \"order_id\": input.get(\"order_id\"),\n"
                    "        \"status\": \"preparing\",\n"
                    "        \"eta_minutes\": random.randint(5, 20)\n"
                    "    }\n\n\n"
                )

            else:
                # Fallback
                f.write("    return {}\n\n\n")

        # Run server
        f.write("if __name__ == '__main__':\n")
        f.write("    mcp.run(transport=\"stdio\")\n")
