"""
AUTO-GENERATED FILE
-------------------
This MCP server was generated automatically from an OpenAPI specification.
Do NOT edit this file manually.
"""

from mcp.server import MCPServer
import uuid
import random

server = MCPServer()

# -----------------------------
# Tool: getMenu
# -----------------------------
@server.tool()
def getMenu(input: dict) -> dict:
    """
    Get pizza menu
    """
    return {
        "menu": [
            {"name": "Margherita", "size": "Medium", "price": 8.99},
            {"name": "Pepperoni", "size": "Large", "price": 12.99},
            {"name": "Veggie", "size": "Small", "price": 7.49},
        ]
    }


# -----------------------------
# Tool: placeOrder
# -----------------------------
@server.tool()
def placeOrder(input: dict) -> dict:
    """
    Place a pizza order
    """
    order_id = str(uuid.uuid4())[:8]

    return {
        "order_id": order_id,
        "eta_minutes": random.randint(15, 30)
    }


# -----------------------------
# Tool: trackOrder
# -----------------------------
@server.tool()
def trackOrder(input: dict) -> dict:
    """
    Track an existing order
    """
    return {
        "order_id": input.get("order_id"),
        "status": "preparing",
        "eta_minutes": random.randint(5, 20)
    }


if __name__ == "__main__":
    server.run()
